
export const ADD_EXPENSE = 'ADD_EXPENSE'
export const EXPENSE_ADDED = 'EXPENSE_ADDED'

export const DELETE_EXPENSE = 'DELETE_EXPENSE'
export const EXPENSE_DELETED = 'EXPENSE_DELETED' 

export const LOAD_EXPENSE = 'LOAD_EXPENSE'
export const EXPENSE_LOADED = 'EXPENSE_LOADED'

export const SEARCH_EXPENSE = 'SEARCH_EXPENSE'
export const EXPENSE_SEARCHED = 'EXPENSE_SEARCHED'

export const UPDATE_EXPENSE = 'UPDATE_EXPENSE'
